### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [gree/flare#39]
I find that include guards like "[APP_H](https://github.com/gree/flare/blob/a3ff1ba45208391ae4465039751241025f36eece/src/lib/app.h#L8)" and "[CLIENT_H](https://github.com/gree/flare/blob/a3ff1ba45208391ae4465039751241025f36eece/src/lib/client.h#L8)" are too short for the safe reuse of your header files.
How do you think about to make [them](http://en.wikipedia.org/wiki/Include_guard#Difficulties "Consistency for include guards") [not only standard-compliant](https://github.com/gree/flare/issues/31 "Identifier clean-up") but also really unique by appending [a kind of UUID](http://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by junjihashimoto** [comment]
Currently, we do not worry about include guards.
(It is because Flare is server and it is not user library/)
If we have  trouble with compilation for these guards,  we will reopen this.
