### ISSUE TITLE
Debian パッケージのリンク切れ

### ISSUE THREAD

**Issue by ledmonster** [gree/flare#43]
Tokyo Cabinet, Flare の Debian パッケージへのリンクが切れています。
- http://labs.gree.jp/data/source/tokyocabinet-dev_1.3.20-1_i386.deb
- http://labs.gree.jp/data/source/flare_1.0.0-1_i386.deb

対象ページ: https://github.com/gree/flare/wiki/Installation-JP

**Comment by junjihashimoto** [comment]
https://github.com/gree/flare/tree/gh-pages/files
こちらから必要なパッケージを参照ください。
よろしくお願いします。
